### ISSUE TITLE
Clipboard provider in Neovim may be unavailable

### ISSUE THREAD

**Issue by bohrshaw** [tommcdo/vim-exchange#37]
I'm in Neovim in a VM without GUI. And a clipboard related error occurred in the function `s:save_reg`.

**Comment by tommcdo** [comment]
Can you be more specific? What is the error message?

I could suppress the error when calling `getreg()`, but I want to make sure it's necessary. In Vim without clipboard support, calling `getreg()` with `'*'` or `'+'` will just return an empty string, no error. I don't have an instance of Neovim without clipboard support to confirm that this behaviour has changed.

**Comment by bohrshaw** [comment]
clipboard: No shell command for communicating with the clipboard found.
    Error detected while processing function <SNR>50_exchange_set..<SNR>50_exchange_get..<SNR>50_save_reg:
    line    1:
    clipboard: provider is not available

Still the same on the latest neovim.

**Comment by tommcdo** [comment]
I'm actually unable to test this. If this change doesn't fix your problem, re-open this issue.
