### ISSUE TITLE
allow count for cxx

### ISSUE THREAD

**Issue by Konfekt** [tommcdo/vim-exchange#41]
How about allowing counts for `cxx` ? For example, the following workaround over here seems to achieve just that:
```vim
onoremap <SID>(underline) _
nmap <expr> cxx '<Plug>(Exchange)' . v:count1 . '<SID>(underline)'
```

**Comment by tommcdo** [comment]
I think this could be extended to support a count across the board. Today it works to use `cx[count]{motion}`, but `[count]cx{motion}` should do the same thing to be consistent with other Vim operators.
