### ISSUE TITLE
support repeating swap operations

### ISSUE THREAD

**Issue by acornejo** [tommcdo/vim-exchange#44]
I often use this plugin to swap function arguments. When doing this I often have to repeat the same operation in various call sites. Unfortunately this plugin doesn't play nicely with vim's repeat operatiorn '.'.

It would be nice to add support for repeat, perhaps by leveraging https://github.com/tpope/vim-repeat

**Comment by wellle** [comment]
For my use cases it usually works. For example with the cursor on the beginning of the first line in
```
f1(a, "s1")
func2(12, "s5")
```
typing `cxIna...` leads to
```
f1("s1", a)
func2("s5", 12)
```
I'm using [targets.vim](https://github.com/wellle/targets.vim) for the next argument text object here. But as far as I can tell vim-exchange seems to handle repetition just fine.

But maybe you have a different use case or flow in mind?

**Comment by tommcdo** [comment]
The plugin can't know what movement commands you've use between marking the first and second exchange operands, so repeating the exchange (which is *two* operations) is impossible. To generalize this, consider what would happen if it tried to repeat an exchange of two non-adjacent text objects that may not even be of the same type (for example, exchange the contents of this string with the paragraph a few lines down). It just doesn't make

There are plugins designed specifically for argument manipulation that are more suited to swapping two adjacent arguments in a repeatable fashion.
