### ISSUE TITLE
support to keep cursor as it was after calling  <plug>(Exchange)

### ISSUE THREAD

**Issue by haolian9** [tommcdo/vim-exchange#56]
context:

* have a map: `vmap X <Plug>(Exchange)`
* key sequence in vim: `viwX`

the problem is:
*  after `viw` the cursor stays at word end
* after `X` the cursor jump to the word start

So I changed map to `vmap X <Plug>(Exchange)E` (appended a E), but sometimes the selection is **==not a word.

The cursor jumping is not really matter too much, but when I noticed it, It becoming annoying more and more ...

**Comment by tommcdo** [comment]
If I'm not mistaken, the cursor moving to the beginning of the selection is the default behavior for operators. For example, see `y` or `gU`.

You might be able to use `` `] `` and the end of your mapping, which jumps to the end of the previous selection.

**Comment by haolian9** [comment]
Thanks for the `` `]`` solution, it works nicely.

**Comment by haolian9** [comment]
It a shame I did not known about `` `]`` before, sorry for the noise, and thank you for the great plugin.
