### ISSUE TITLE
How to Reset

### ISSUE THREAD

**Issue by chettri015** [tommcdo/vim-exchange#59]
How do I reset? I tried uninstalling, deleting all the supporting files, and reinstalling, and no luck.
I mess up the setting, and now I can't change any setting.

**Comment by tommcdo** [comment]
Hello! I'm happy to help.

Can you please clarify what you mean by reset? It would be helpful if you could describe the following:

1. What you did
2. What you expected to happen
3. What actually happened

**Comment by chettri015** [comment]
Thank you for your quick reply. 
I would like it to reset to the default setting. 
I changed a bunch of setting from the menu bar; now I can only see the clipboard history. 
I no longer see preferences when I click maccy  icon on the menu bar.

**Comment by tommcdo** [comment]
Are you having an issue with [Maccy](https://github.com/p0deje/Maccy)?

This issue tracker is for a Vim plugin.
